### ISSUE TITLE
Rewrite the authz part

### ISSUE THREAD

**Issue by dasJ** [inishchith/autoenv#130]
When authenticating a .env file (or a unload file in the future), the y/n is not enough anymore.

Instead, it would be useful if users could **always** approve/decline a .env file.
- [ ] We should use stty and dd instead of read (#128)
- [ ] Users must be able to save that they have declined running a .env file (#21)
- [ ] Users should be able to allow/decline .env files even after changing

This leaves us with these options for each .env file:
- Allow this time
- Allow always
- Allow always, even when changed
- Decline this time
- Decline always
- Decline always, even when changed

It's hard to name the options now. My current proposal is:

```
y - Allow this time
Y - Allow always
a - Allow always, even when changed
n - Decline this time
N - Decline always
A - Decline always, even when changed
```

Which would result in the help message:

```
...
autoenv:   --- (end contents) -----------------------------------------
autoenv:
autoenv: Allow: [y] This time [Y] Always [a] Always, even when changed
autoenv: Deny:  [n] This time [N] Always [A] Always, even when changed
autoenv:
autoenv: Your coice?
```

Where [n] would be the default value.
The default value could be set with something like `AUTOENV_DEFAULT_ANSWER`.

**Comment by dasJ** [comment]
To store the new values, the authorized file needs a new syntax while staying compatible with the previous syntax.

## Suggested syntax:
```
[allowed]:[hash]:[path]
```
Where `[allowed]` can either be `y` or `n`.
`[hash]` may be `SKIP` which allows/denies the file even when it was changed.

The filename is moved to the end so it can contain colons.

So a file might look like this:
```
y:074a866c606abbd2051c8ffad840e8d407c49823:/i/am/allowed/if/i/don't/change
n:3cb83fa2e43208ad89acabfa4e6678f8c09ff7a4:/i/am/denied/if/i/don't/change
y:SKIP:/i/am/always/allowed
n:SKIP:/i/am/always/denied
/we/still/support/the/old/syntax:334fc4857b38918a32cbdef9717ec807b7366811
```

**Comment by ernstki** [comment]
Out of curiosity, what is the use case for allowing the `.env` file to be automatically authorized even after changing? Are people modifying them frequently enough that answering 'y' every time gets annoying? I typically edit the `.env` only a couple of times per project, and I find the confirmation from autoenv reassuring.

Getting in the habit of answering "[Y] Always" might lead someone to say "Y" for /tmp, and I thought that was the whole reason for prompting in the first place: to prevent someone from slipping a malicious `.env` into a world-writable directory you visit frequently.

I definitely see the value in "ignore permanently" though. Wouldn't a "y/n/i" prompt along with the addition of a `.autoenv_ignored` (as mentioned in #21) be a nice, simple solution, as long as the "Ignore" option informed you that you'd have to manually edit `~/.autoenv_ignored` in order to "un-ignore" a specific .env?

**Comment by dasJ** [comment]
I like the idea of telling the user to un-ignore the file.
The "Always, even when changed" option (maybe add a big warning label) is useful in a collaborating but trusted environment.
If my team at work uses a git repository containing a .env file, and each commit needs to be approved, the probability is low that someone writes bad code to the .env file.
